config/routes.rb
Oscurrency::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :person_sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :member_preferences
  resources :neighborhoods, :only => [:show]
  resources :invitations, :only => [:edit, :update]
  resources :privacy_settings, :only => [:update]
  resources :posts, :only => [:index]

  # XXX in 2.3.x, this was easier -> map.resources :transacts, :as => "transacts/:asset"
  get    "transacts(/:asset)(.:format)"          => "transacts#index",   :as => 'transacts'
  get    "transacts(/:asset)/new"      => "transacts#new",     :as => 'new_transact'
  get    "transacts(/:asset)/:id(.:format)"      => "transacts#show",    :as => 'transact'
  post   "transacts(/:asset)(.:format)"          => "transacts#create",  :as => 'transacts'
  #get    "transacts/[:asset]/:id/edit" => "transacts#edit",    :as => 'edit_transact'
  #put    "transacts/[:asset]/:id"      => "transacts#update",  :as => 'transact'
  delete "transacts(/:asset)/:id(.:format)"      => "transacts#destroy", :as => 'transact'

  resources :groups, :shallow => true do
    member do
      post :join
      post :leave
      get :people
      get :exchanges
      get :members
      get :graphs
      get :photos
      post :new_photo
      post :save_photo
      delete :delete_photo
    end
    resources :memberships
    resources :reqs
    resources :offers
    resource :forum
  end

  resources :bids
  resources :reqs do
    member do 
      post :deactivate
    end
    resources :bids
  end

  resources :offers do
    member do
      get :new_photo
      post :save_photo
    end
  end
  resources :categories

  resources :memberships do
    member do
      delete :unsuscribe
      post :suscribe
    end
  end

  resources :searches
  resources :activities
  resources :connections
  resources :photos do
    collection do
      get :default_profile_picture
      put :update_default_profile_picture
      get :default_group_picture
      put :update_default_group_picture
    end
  end
  resources :messages do
    collection do
      get :sent
      get :trash
      get :recipients
    end
    member do
      get :reply
      put :undestroy
    end
  end
  resources :people do
    member do
      get :verify_email
      get :su
      get :unsu
      get :invite
      post :send_invite
      get :common_contacts
    end
    resources :messages
    resources :accounts
    resources :exchanges
    resources :addresses do
      member do
        post :choose
      end
    end
    resources :photos
    resources :connections
  end

  match 'people/verify/:id' => 'people#verify_email'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  match '/signup' => 'people#new', :as => :signup
  match '/login' => 'person_sessions#new', :as => :login
  match '/logout' => 'person_sessions#destroy', :as => :logout
  match '/refreshblog' => 'feed_posts#refresh_blog', :as => :refreshblog
  match '/about' => 'home#about', :as => :about
  match '/practice' => 'home#practice', :as => :practice
  match '/steps' => 'home#steps', :as => :steps
  match '/questions' => 'home#questions', :as => :questions
  match '/contact' => 'home#contact', :as => :contact
  match '/agreement' => 'home#agreement', :as => :agreement
  resources :oauth_clients
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth/token' => 'oauth#token', :as => :token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/scopes' => 'transacts#scopes', :as => :scopes
  match '/oauth/revoke' => 'oauth#revoke', :as => :revoke
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/about_user' => 'transacts#about_user', :as => :about_user
  match '/user_info' => 'transacts#user_info', :as => :user_info
  match '/wallet' => 'transacts#wallet', :as => :wallet
  match '/.well-known/host-meta' => 'home#host_meta', :as => :host_meta
  match '/home/show/:id' => 'home#show'
  root :to => 'home#index'
  match '/' => 'home#index', :as => :home
end

app/models/membership.rb
require 'will_paginate/array'

class Membership < ActiveRecord::Base
  extend ActivityLogger
  extend PreferencesHelper

  scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0"} }
  scope :active, :include => :person, :conditions => {'people.deactivated' => false}
  scope :listening, :include => [:member_preference, :person], :conditions => {'people.deactivated' => false, 'member_preferences.forum_notifications' => true}

  belongs_to :group
  belongs_to :person
  has_one :member_preference
  has_many :activities, :as => :item #, :dependent => :destroy

  validates_presence_of :person_id, :group_id
  before_create :add_default_roles
  after_create :create_member_preference

  # Status codes.
  ACCEPTED  = 0
  INVITED   = 1 # deprecated
  PENDING   = 2

  ROLES = %w[individual admin moderator org point_of_sale_operator]
  EXCLUDE_ROLES = %w[individual moderator org] # reserved for future use

  class << self
    def search_by(text)
      includes(:person).where(Person.arel_table[:name].matches("%#{text}%").or(Person.arel_table[:business_name].matches("%#{text}%")).or(Person.arel_table[:description].matches("%#{text}%")))
    end

    # For issue #272, people should be ordered by display name(display_name in person.rb) which is business_name or name
    # The following sql is for getting business_name + name
    # case when people.business_name is null then '' else people.business_name end) || people.name
    def custom_search(category,group,page,posts_per_page,search=nil)
      unless category
        group.memberships.active.search_by(search).paginate(:page => page,
                                                            :conditions => ['status = ?', Membership::ACCEPTED],
                                                            :order => "lower((case when people.business_name is null then '' else people.business_name end) || people.name) ASC",
                                                            :include => :person,
                                                            :per_page => posts_per_page)
      else
        category.people.all(:joins => :memberships,
                            :select => "people.*,memberships.id as categorized_membership",
                            :conditions => {:memberships => {:group_id => group.id},
                                            :people => {:deactivated => false}},
                            :order => "lower((case when people.business_name is null then '' else people.business_name end) || people.name) ASC"
        ).map {|p| Membership.find(p.categorized_membership)}.paginate(:page => page,
                                                                       :conditions => ['status = ?', Membership::ACCEPTED],
                                                                       :include => :person,
                                                                       :per_page => posts_per_page)
      end
    end
  end

  def account
    group.adhoc_currency? ? person.account(group) : nil
  end

  def add_default_roles
    group.default_roles.each do |default_role|
      self.add_role(default_role)
    end
  end

  def create_member_preference
    MemberPreference.create(:membership => self)
  end

  # Accept a membership request (instance method).
  def accept
    Membership.accept(person, group)
  end

  def breakup
    Membership.breakup(person, group)
  end

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def add_role(new_role)
    a = self.roles
    a << new_role
    self.roles = a
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def is?(role)
    roles.include?(role.to_s)
  end

  class << self

    # Return true if the person is member of the group.
    def exist?(person, group)
      where(:person_id => person, :group_id => group).exists?
    end

    # Make a pending membership request.
    def request(person, group, send_mail = nil)
      send_mail ||= global_prefs.email_notifications?
      unless person.groups.include?(group) or Membership.exist?(person, group)
        if group.public? or group.private?
          membership = nil
          transaction do
            membership = create(:person => person, :group => group, :status => PENDING)
            after_transaction { PersonMailerQueue.membership_request(membership) } if send_mail
          end
          if group.public?
            Membership.accept(person, group)
            after_transaction { PersonMailerQueue.membership_public_group(membership) } if send_mail
          end
        end
        true
      end
    end

    def invite(person, group, send_mail = nil)
      if send_mail.nil?
        send_mail = global_prefs.email_notifications?
      end
      if Membership.exist?(person, group)
        nil
      else
        transaction do
          invitation = Invitation.create(person: person, group: group)
          if send_mail
            after_transaction { PersonMailerQueue.invitation_notification(invitation) }
          end
        end
        true
      end
    end

    # Accept a membership request.
    def accept(person, group)
      transaction do
        accepted_at = Time.now
        accept_one_side(person, group, accepted_at)
      end
      log_activity(mem(person, group))
    end

    def breakup(person, group)
      transaction do
        destroy(mem(person, group))
      end
    end

    def mem(person, group)
      where(:person_id => person, :group_id => group).first
    end

    def accepted?(person, group)
      where(:person_id => person, :group_id => group, :status => ACCEPTED).exists?
    end

    def pending?(person, group)
      where(:person_id => person, :group_id => group, :status => PENDING).exists?
    end

    # private

    # Update the db with one side of an accepted connection request.
    def accept_one_side(person, group, accepted_at)
      mem = mem(person, group)
      mem.status = ACCEPTED
      mem.accepted_at = accepted_at
      mem.add_role('individual')
      mem.save

      if person.accounts.find(:first,:conditions => ["group_id = ?",group.id]).nil?
        account = Account.new( :name => group.name ) # group name can change
        account.balance = Account::INITIAL_BALANCE
        account.person = person
        account.group = group
        account.credit_limit = group.default_credit_limit
        account.save
      end
    end

    def log_activity(membership)
      activity = Activity.create!(:item => membership, :person => membership.person)
      add_activities(:activity => activity, :person => membership.person)
    end
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_filter :login_required
  load_resource :group
  load_and_authorize_resource :membership, :through => :group, :shallow => true

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    respond_to do |format|
      format.html {redirect_to @membership.group}
    end
  end

  def index
    @selected_category = params[:category_id].nil? ? nil : Category.find(params[:category_id])
    @selected_neighborhood = params[:neighborhood_id].nil? ? nil : Neighborhood.find(params[:neighborhood_id])

    @authorized = @group.authorized_to_view_members?(current_person)
    if @authorized
      @memberships = Membership.custom_search(@selected_neighborhood || @selected_category, 
                                            @group, 
                                            params[:page], 
                                            ajax_posts_per_page, 
                                            params[:search]
                                            )
    else
      flash[:notice] = t('notice_member_to_view_people')
      @memberships = Membership.where('1=0').paginate(:page => 1, :per_page => ajax_posts_per_page)
    end

    respond_to do |format|
      format.js {render :action => 'reject' if not request.xhr?}
    end
  end

  def show
    @group = @membership.group
    @current_membership = Membership.mem(current_person,@membership.group)
    @person = @membership.person
    @account = @person.account(@membership.group)
    @offers = @person.offers.active
    @reqs = @person.reqs.all_active
    respond_to do |format|
      if @group.authorized_to_view_members?(current_person)
        format.js {render :action => 'reject' if not request.xhr?}
        format.html { redirect_to('/groups/' + @membership.group.id.to_s + '#memberships/' + @membership.id.to_s)}
      else
        raise CanCan::AccessDenied.new("Not authorized!", :read, Membership)
      end
    end
  end

  def edit
    @account = @membership.account
  end
  
  def create

    respond_to do |format|
      @hr = Membership.request(current_person, @group)
      if @hr
        if @group.public?
          flash[:notice] = t('notice_you_have_joined') + " '#{@group.name}'"
        else
          flash[:notice] = t('notice_membership_request_sent')
        end
        format.html { redirect_to(home_url) }
        format.js
      else
        # This should only happen when people do something funky
        # like trying to join a group that has a request pending
        flash[:notice] = t('notice_membership_invalid')
        format.html { redirect_to(home_url) }
        format.js
      end
    end
  end
  
  def update
    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        flash[:notice] = 'Membership was successfully updated.'
        format.html { redirect_to(members_group_path(@membership.group)) }
      else
        format.html { render :action => "edit" }
      end
    end  
  end
  
  def destroy
    @membership.breakup
    
    respond_to do |format|
      flash[:notice] = t('success_you_have_left_the_group') + " #{@membership.group.name}"
      format.html { redirect_to( person_url(current_person)) }
      format.js
    end
  end
  
  def unsuscribe
    @membership.breakup
    
    respond_to do |format|
      flash[:success] = t('success_you_have_unsubscribed') + " '#{@membership.person.display_name}' #{t('success_from_group')} '#{@membership.group.name}'"
      format.html { redirect_to(members_group_path(@membership.group)) }
    end
  end
  
  def suscribe
    @membership.accept
    after_transaction { PersonMailerQueue.membership_accepted(@membership) }

    respond_to do |format|
      flash[:success] = t('success_you_have_accepted') + " '#{@membership.person.display_name}' #{t('success_for_group')} '#{@membership.group.name}'"
      format.html { redirect_to(members_group_path(@membership.group)) }
    end
  end
  
end

app/helpers/memberships_helper.rb
module MembershipsHelper
  def membership_link(member, html_options = nil)
    unless (member.nil? || member.person.nil?)
      text = member.person.display_name
    else
      text = "(member left!)"
    end
    link_to(h(text), member, html_options)
  end
end

app/views/memberships/_member.html.erb
<% person = member.person %>
<li class="vcard person">
  <div class="profile-image">
    <%= image_link person, :link => member, :link_options => {:class => "show-follow"}, :image_options => {:class => "photo"}, :image => :thumbnail %>
  </div>
  <div class="col_content">
    <p><%= membership_link member, :class => "url fn show-follow" %>&nbsp;<%= organization_image(person) if global_prefs.display_orgicon? %></p>
    <% if defined? short %>
      <%= display person.listed_categories, :class => "meta" %>
      <%= display truncate(person.description, :length => 150), :class => "muted" %>
    <% else %>
      <%= display person.description, :class => "note" %>
    <% end %>
  </div>
</li>

app/views/memberships/_members_canvas.html.erb
      <%= will_paginate(@memberships, :renderer => BootstrapPaginationHelper::LinkRenderer) %>
      <ul class="list activity full">
        <%= render :partial => '/memberships/member', :collection => @memberships, :locals => {:short => true} %>
      </ul>
      <div style='clear:both;'></div>
      <%= will_paginate(@memberships, :renderer => BootstrapPaginationHelper::LinkRenderer) %>

app/views/memberships/_membership_full.html.erb
  <strong style="display:inline">Associated with&nbsp;:&nbsp;</strong><%= display @person.listed_categories, :class => "meta", :style => 'display:inline;' %>
  
  <div class="profile vcard">
    
    <!-- Profile title -->
    <%- if @person.openid_identifier.nil? -%>
      <h2>
        <%= t('people.show.header') %> <span class="fn n"><%= h @person.display_name %></span>&nbsp;<%= organization_image(@person) %><%= waiting_image %>
      </h2>
    <%- else -%>
      <h2>
        <%= t('people.show.header') %> <span class="fn n"><%= link_to h(@person.display_name), @person.openid_identifier, :title => @person.openid_identifier %></span>&nbsp;<%= image_tag("login-bg.gif") %><%= organization_image(@person) %>&nbsp;<%= waiting_image %>
      </h2>
    <%- end -%><!-- profile title -->

    <%- if admin? and not @person.active? -%>
      <p class="alert alert-error"><%= t('people.show.not_active') %></p>
    <%- end -%>

    <!-- display warning messages -->
    <%- if current_person?(@person) -%>
      <%- if current_person.description.blank? -%>
        <div class="alert alert-error">
          <%= t('people.show.description_blank') %>
          <%= link_to t('people.show.add_description'),
                      edit_person_path(@person) %>
        </div>
      
      <%- else -%>
        <div class="alert">
          <%= t('people.show.own_profile') %>
          <%= link_to t('people.show.edit_it'), edit_person_path(@person) %>
        </div>
      <%- end -%>

      <%- if current_person.address && Person::DEFAULT_ZIPCODE_STRING == current_person.address.zipcode_plus_4 %>
        <div class="alert alert-error">
          <%= link_to t('people.show.update_location'),
                      edit_person_path(@person) %>. 
          <%= t('people.show.address_remain_private') %>
        </div>
      <%- end -%>
    
    <%- end -%><!-- display warning messages -->


      <div class="row-fluid">

        <div class="span3">
          <%= image_tag @person.main_photo, :class => "profile-image photo",
                                            :alt => h(@person.display_name) %>
        </div>

        <div class="span5">
          <ul>
            <%= render :partial => 'shared/neighborhood', :collection => @person.neighborhoods %>
          </ul>
          
          
          <% if @person.phoneprivacy? %>
            <% unless @person.phone.nil? %>
              <div>
                <%= image_tag "icons/phone.gif", :class => "icon", :alt => "Phone" %> <span class="small"><%= t('people.show.phone') %></span> <span class="added small"><%= h @person.phone %></span>
              </div>
            <%- end -%>
          <%- end -%>
          <% @person.shared_addresses.each do |shared_address| %>
            <div>
              <%= image_tag "icons/home.gif", :class => "icon", :alt => "Address" %>
                <span class="medium"><%= h shared_address %></span>
            </div>
          <% end %>

          <% if @person.web_site_url %>
            <div>
              <%= image_tag "icons/new_window.gif", :class => "icon", :alt => "Website" %>
                <span class="small"><%= t('people.edit.web_site_url') %></span>
                <span class="small"><%= h @person.web_site_url %></span>
            </div>
          <%- end -%>

          <%= markdown(@person.description) %>
        
        </div>

        <div class="span4">
          <div class="toolbox">
            <ul class="tools">
            
              <%- if @person.org %>
                <li>
                  <span class="label"><%= t('groups.show.contact') %></span>: <%= @person.name %>
                </li>
              <%- end %>

              <%- unless current_person?(@person) -%>
                <%- if logged_in? -%>
                  <%- if @membership.group.adhoc_currency? -%>
                      
                    <li>
                      <%= exchange_link @person, @membership.group, :transact => 'credit', :class => 'show-follow' %>
                    </li>
                      
                    <%- if @current_membership.is?(:point_of_sale_operator) || @current_membership.is?(:admin) %>
                      <li>
                        <%= exchange_link @person, @membership.group, :transact => 'debit', :class => 'show-follow' %>
                      </li>
                    <%- end -%>
                    
                  <%- end -%>
                    
                  <li>
                    <%= email_link @person %>
                  </li>
                  <%- if current_person.own_groups.length > 0 %>
                    <li><%= link_to "Invite to group", invite_person_path(@person) %>
                  <%- end -%>
                    
                  <%- if @membership.group.adhoc_currency? -%>
                    <%= render :partial => 'shared/account', :locals => {:account => @account, :html_classes => 'show-follow'} %>
                  <%- end -%>
                <%- end -%>
                
                <%- if current_person.admin? -%>
                  <li>
                    <%= link_to t('people.show.switch_user'), su_person_path(@person) %>
                  </li>
                  <li>
                    <%- activity = @person.deactivated? ? "activate" : "deactivate" -%>
                    <%= link_to activity, 
                                person_path(@person, :task => "deactivated"),
                                :method => :put %>
                  </li>
                <%- end -%>
                
              <% else -%>
                <%- if logged_in? -%>
                  <%- if @membership.group.adhoc_currency? -%>
                    <%= render :partial => 'shared/account', :locals => {:account => @account, :html_classes => 'show-follow'} %>
                  <%- end -%>
                <%- end -%>
              <%- end -%>
            </ul>
          </div>
        </div> <!-- span4 -->



      </div> <!-- row fluid -->
  
  </div> <!-- profile v-card -->

  <hr/>

  <div class="row-fluid">

    <div class="activity-container">
      <h3>Offers</h3>
      
      <% if @offers.empty? %>
        <%= t('offers.index.nooffers') %>
      <% else %>
        <% @offers.each do |offer| %>
          <div class="activity-inner">  
            <h4><%= h offer.name %><%= waiting_image %></h4>
            <ul class="list activity full">
              <%= render :partial => offer, :locals => {:full => false} %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>


  <br/>
  <br/>

  <div class="activity-container">
    <h3>Requests</h3>
    <% if @reqs.empty? %>
      <%= t('reqs.home.menu._dashboard.no_active_requests') %>
    <% else %>
      <% @reqs.each do |req| %>
        <div class="activity-inner">
          <h4><%= h req.name %><%= waiting_image %></h4>
          <ul class="list activity full">
            <%= render :partial => req, :locals => {:full => false} %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>

  <br/>
  <br/>
<%- unless @membership.group.private_txns? %>
  <%- unless @person.recent_activity.empty? -%>
  
    <div class="activity-container">
      <h3><%= t('people._recent_exchanges.header') %></h3>
      
      <%- unless @person.last_logged_in_at.nil? or current_person?(@person) -%>

        <p class="meta">
          <%= @person.display_name %> <%= t('last_logged_in') %>
          <%= t 'ago_time', :date => time_ago_in_words(@person.last_logged_in_at) %> 
        </p>    

      <%- end -%>

      <ul class="list activity full">
         <%= render :partial => 'shared/exchange',
                    :collection => @person.received_group_exchanges(@membership.group) %>
      </ul>

    </div>
    

  <%- end -%> 
<%- end -%>

app/views/memberships/create.js.erb
<%= render :partial => '/shared/flash_messages', :locals => {:canvas_id => 'membership_wrapper'} %>
<% if @hr %>
$('a#leave_group').attr('href','<%= membership_path(Membership.mem(current_person, @group)) %>');
$('a#leave_group').parent().show();
<% else %>
$('a#join_group').parent().show();
<% end %>

app/views/memberships/destroy.js.erb
<%= render :partial => '/shared/flash_messages', :locals => {:canvas_id => 'membership_wrapper'} %>
$('a#join_group').parent().show();

app/views/memberships/edit.html.erb
<h2>Edit membership for <%= h @membership.person.display_name %></h2>
<%= form_for(@membership) do |f| %>
  <% for role in (Membership::ROLES - Membership::EXCLUDE_ROLES) %>
    <%= check_box_tag "membership[roles][]", role, @membership.roles.include?(role) %>
    <%=h role.humanize %><br />
  <% end %>
  <%= hidden_field_tag "membership[roles][]", "" %>
  <br />
  <%= f.submit t('button_update'), class: 'btn btn-primary' %>
<% end %>
<% if @account %>
  <h2>Edit account for <%= h @membership.person.display_name %></h2>
  <%= bootstrap_form_for @account, :url => person_account_path(@membership.person,@account), :html => {:method => :put} do |f| %>
    <%= f.text_field :credit_limit, label: 'Credit Limit',:help => @account.group.unit || Group.find(global_prefs.default_group_id).unit, :size => 5 %>
    <%= f.text_field :offset, label: 'Legacy Balance', :help => @account.group.unit || Group.find(global_prefs.default_group_id).unit, :size => 5 %>
    <%= f.control_group :reserve do %>
      <%= f.check_box :reserve, label: 'Reserve?' %>
    <% end %>
    <%= f.text_field :reserve_percent, label: 'Reserve Percent', :help => '(must be between 0 and 1)', :size => 5 %>
    <%= f.submit t('button_update'), class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/memberships/index.js.erb
<%- if @authorized -%>
$('#people_filter').show();
$('#people_canvas').html("<%= escape_javascript(render :partial => 'members_canvas') %>");
$('#posts_per_page').show();
<%- else -%>
$('#people_canvas').html("");
<%= render :partial => '/shared/flash_messages', :locals => {:canvas_id => 'people_canvas'} %>
<%- end -%>

app/views/memberships/show.html.erb
<p>
  <b>Person:</b>
  <%=h @membership.person_id %>
</p>

<p>
  <b>Group:</b>
  <%=h @membership.group_id %>
</p>

<p>
  <b>Status:</b>
  <%=h @membership.status %>
</p>

<p>
  <b>Accepted at:</b>
  <%=h @membership.accepted_at %>
</p>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/show.js.erb
$('#people_filter').hide();
$('#posts_per_page').hide();
$('#people_canvas').html('<%= escape_javascript(render :partial => 'membership_full', :locals => {:membership => @membership, :offers => @offers, :reqs => @reqs}) %>');
$('#people_canvas').linkify();
<%= render :partial => '/shared/flash_messages', :locals => {:canvas_id => 'people_canvas'} %>