config/routes.rb
Oscurrency::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :person_sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :member_preferences
  resources :neighborhoods, :only => [:show]
  resources :invitations, :only => [:edit, :update]
  resources :privacy_settings, :only => [:update]
  resources :posts, :only => [:index]

  # XXX in 2.3.x, this was easier -> map.resources :transacts, :as => "transacts/:asset"
  get    "transacts(/:asset)(.:format)"          => "transacts#index",   :as => 'transacts'
  get    "transacts(/:asset)/new"      => "transacts#new",     :as => 'new_transact'
  get    "transacts(/:asset)/:id(.:format)"      => "transacts#show",    :as => 'transact'
  post   "transacts(/:asset)(.:format)"          => "transacts#create",  :as => 'transacts'
  #get    "transacts/[:asset]/:id/edit" => "transacts#edit",    :as => 'edit_transact'
  #put    "transacts/[:asset]/:id"      => "transacts#update",  :as => 'transact'
  delete "transacts(/:asset)/:id(.:format)"      => "transacts#destroy", :as => 'transact'

  resources :groups, :shallow => true do
    member do
      post :join
      post :leave
      get :people
      get :exchanges
      get :members
      get :graphs
      get :photos
      post :new_photo
      post :save_photo
      delete :delete_photo
    end
    resources :memberships
    resources :reqs
    resources :offers
    resource :forum
  end

  resources :bids
  resources :reqs do
    member do 
      post :deactivate
    end
    resources :bids
  end

  resources :offers do
    member do
      get :new_photo
      post :save_photo
    end
  end
  resources :categories

  resources :memberships do
    member do
      delete :unsuscribe
      post :suscribe
    end
  end

  resources :searches
  resources :activities
  resources :connections
  resources :photos do
    collection do
      get :default_profile_picture
      put :update_default_profile_picture
      get :default_group_picture
      put :update_default_group_picture
    end
  end
  resources :messages do
    collection do
      get :sent
      get :trash
      get :recipients
    end
    member do
      get :reply
      put :undestroy
    end
  end
  resources :people do
    member do
      get :verify_email
      get :su
      get :unsu
      get :invite
      post :send_invite
      get :common_contacts
    end
    resources :messages
    resources :accounts
    resources :exchanges
    resources :addresses do
      member do
        post :choose
      end
    end
    resources :photos
    resources :connections
  end

  match 'people/verify/:id' => 'people#verify_email'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  match '/signup' => 'people#new', :as => :signup
  match '/login' => 'person_sessions#new', :as => :login
  match '/logout' => 'person_sessions#destroy', :as => :logout
  match '/refreshblog' => 'feed_posts#refresh_blog', :as => :refreshblog
  match '/about' => 'home#about', :as => :about
  match '/practice' => 'home#practice', :as => :practice
  match '/steps' => 'home#steps', :as => :steps
  match '/questions' => 'home#questions', :as => :questions
  match '/contact' => 'home#contact', :as => :contact
  match '/agreement' => 'home#agreement', :as => :agreement
  resources :oauth_clients
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth/token' => 'oauth#token', :as => :token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/scopes' => 'transacts#scopes', :as => :scopes
  match '/oauth/revoke' => 'oauth#revoke', :as => :revoke
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/about_user' => 'transacts#about_user', :as => :about_user
  match '/user_info' => 'transacts#user_info', :as => :user_info
  match '/wallet' => 'transacts#wallet', :as => :wallet
  match '/.well-known/host-meta' => 'home#host_meta', :as => :host_meta
  match '/home/show/:id' => 'home#show'
  root :to => 'home#index'
  match '/' => 'home#index', :as => :home
end

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%- if global_prefs.app_name.blank? -%>
      <title>Insoshi Open Source Social Networking Platform</title>
    <%- else -%>
      <title><%= global_prefs.app_name %></title>
    <%- end -%>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield :head %>    
  </head>
  <body class="<%= @body %>">
    <div id="header-wrap">
      <div id="header">
        <h1>
        <%= global_prefs.app_name %>
        </h1>
        <ul id="nav">
        </ul>
        
          <p class="welcome">
            <%- if logged_in? -%>
              Welcome, <%= h current_person.display_name %>!
              (<%= link_to "Sign out", logout_path %>)
              <%- if current_person.admin? -%>
                <br />
                <%= link_to("Refresh Blog Feed", '/refreshblog') %> | 
                <%= link_to("Standard view", home_path) %>
              <%- end -%>
            <%- else -%>
              <%= link_to "Sign in", login_path %> or
              <%= link_to "Sign up", signup_path %>
              <%- if global_prefs.can_send_email? -%>
              <br />
              <%= link_to "I forgot my password",
                           new_password_reminder_path %>
              <%- end -%>             
            <%- end -%>
          </p>
      </div>
    </div>
    
    <div id="wrap">
      <div id="content">
        <%- if global_prefs.demo? -%>
          <p class="error" style="font-weight: bold;">
            This is a demonstration site. 
            Data may be modified or removed without warning.
          </p>
        <%- end -%>
        <% flash.each do |key, msg| %>
          <%= content_tag :p, msg.html_safe, :class => "alert alert-#{key}" %>
        <% end %>     
        <%= yield %>
        <div id="footer">
          <p>
		<%= render :partial => 'shared/powered_by' %>
          </p>
        </div>
      </div>
      <%- if Rails.env.development? -%>
        <div><%= render :partial => 'shared/debug' %></div>
      <%- end -%> 
    </div>
    <%= global_prefs.analytics %>
  </body>
</html>