config/routes.rb
Oscurrency::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :person_sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :member_preferences
  resources :neighborhoods, :only => [:show]
  resources :invitations, :only => [:edit, :update]
  resources :privacy_settings, :only => [:update]
  resources :posts, :only => [:index]

  # XXX in 2.3.x, this was easier -> map.resources :transacts, :as => "transacts/:asset"
  get    "transacts(/:asset)(.:format)"          => "transacts#index",   :as => 'transacts'
  get    "transacts(/:asset)/new"      => "transacts#new",     :as => 'new_transact'
  get    "transacts(/:asset)/:id(.:format)"      => "transacts#show",    :as => 'transact'
  post   "transacts(/:asset)(.:format)"          => "transacts#create",  :as => 'transacts'
  #get    "transacts/[:asset]/:id/edit" => "transacts#edit",    :as => 'edit_transact'
  #put    "transacts/[:asset]/:id"      => "transacts#update",  :as => 'transact'
  delete "transacts(/:asset)/:id(.:format)"      => "transacts#destroy", :as => 'transact'

  resources :groups, :shallow => true do
    member do
      post :join
      post :leave
      get :people
      get :exchanges
      get :members
      get :graphs
      get :photos
      post :new_photo
      post :save_photo
      delete :delete_photo
    end
    resources :memberships
    resources :reqs
    resources :offers
    resource :forum
  end

  resources :bids
  resources :reqs do
    member do 
      post :deactivate
    end
    resources :bids
  end

  resources :offers do
    member do
      get :new_photo
      post :save_photo
    end
  end
  resources :categories

  resources :memberships do
    member do
      delete :unsuscribe
      post :suscribe
    end
  end

  resources :searches
  resources :activities
  resources :connections
  resources :photos do
    collection do
      get :default_profile_picture
      put :update_default_profile_picture
      get :default_group_picture
      put :update_default_group_picture
    end
  end
  resources :messages do
    collection do
      get :sent
      get :trash
      get :recipients
    end
    member do
      get :reply
      put :undestroy
    end
  end
  resources :people do
    member do
      get :verify_email
      get :su
      get :unsu
      get :invite
      post :send_invite
      get :common_contacts
    end
    resources :messages
    resources :accounts
    resources :exchanges
    resources :addresses do
      member do
        post :choose
      end
    end
    resources :photos
    resources :connections
  end

  match 'people/verify/:id' => 'people#verify_email'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  match '/signup' => 'people#new', :as => :signup
  match '/login' => 'person_sessions#new', :as => :login
  match '/logout' => 'person_sessions#destroy', :as => :logout
  match '/refreshblog' => 'feed_posts#refresh_blog', :as => :refreshblog
  match '/about' => 'home#about', :as => :about
  match '/practice' => 'home#practice', :as => :practice
  match '/steps' => 'home#steps', :as => :steps
  match '/questions' => 'home#questions', :as => :questions
  match '/contact' => 'home#contact', :as => :contact
  match '/agreement' => 'home#agreement', :as => :agreement
  resources :oauth_clients
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth/token' => 'oauth#token', :as => :token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/scopes' => 'transacts#scopes', :as => :scopes
  match '/oauth/revoke' => 'oauth#revoke', :as => :revoke
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/about_user' => 'transacts#about_user', :as => :about_user
  match '/user_info' => 'transacts#user_info', :as => :user_info
  match '/wallet' => 'transacts#wallet', :as => :wallet
  match '/.well-known/host-meta' => 'home#host_meta', :as => :host_meta
  match '/home/show/:id' => 'home#show'
  root :to => 'home#index'
  match '/' => 'home#index', :as => :home
end

app/models/group.rb
require 'texticle/searchable'

class Group < ActiveRecord::Base
  include ActivityLogger
  extend PreferencesHelper
  
  validates_presence_of :name, :person_id

  attr_accessible :name, :description, :mode, :unit, :adhoc_currency, :default_credit_limit
  attr_accessible :asset, :private_txns, :enable_forum, :display_balance, :display_earned, :display_paid
  attr_accessible :default_roles

  has_one :forum
  has_one :privacy_setting
  has_many :reqs, :conditions => ["biddable = ?",true], :order => "created_at DESC"
  has_many :offers, :order => "created_at DESC"
  has_many :photos, :as => :photoable, :dependent => :destroy, :order => "created_at"
  has_many :exchanges, :order => "created_at DESC"
  has_many :exchange_and_fees, :order => "created_at DESC"
  has_many :memberships, :dependent => :destroy
  has_many :accounts, :dependent => :destroy
  has_many :people, :through => :memberships, 
    :conditions => "status = 0", :order => "name DESC"
  has_many :pending_request, :through => :memberships, :source => "person",
    :conditions => "status = 2", :order => "name DESC"
  
  belongs_to :owner, :class_name => "Person", :foreign_key => "person_id"
  
  has_many :activities, :as => :item, :dependent => :destroy

  validates_uniqueness_of :name
  validates_uniqueness_of :unit, :allow_nil => true
  validates_uniqueness_of :asset, :allow_nil => true
  validates_format_of :asset, :with => /^[-\.a-z0-9_]+$/i, :allow_blank => true
  validate :changing_asset_name_only_allowed_if_empty
  after_create :create_owner_membership
  after_create :create_forum
  after_create :create_privacy_setting
  after_create :log_activity
  before_update :update_member_credit_limits
  
  extend Searchable(:name, :description)
  
  # GROUP modes
  PUBLIC = 0
  PRIVATE = 1
  
  def get_groups_modes
    modes = []
    modes << ["Public",PUBLIC]
    modes << ["Membership approval required",PRIVATE] unless default_group?
    return modes
  end

  def default_group?
    id == Group.global_prefs.default_group_id
  end

  def default_roles=(roles)
    self.roles_mask = (roles & Membership::ROLES).map { |r| 2**Membership::ROLES.index(r) }.sum
  end

  def default_roles
    Membership::ROLES.reject do |r|
      ((roles_mask || 0) & 2**Membership::ROLES.index(r)).zero?
    end
  end
  
  class << self

    def name_sorted_and_paginated(page = 1)
      paginate(:page => page,
               :per_page => RASTER_PER_PAGE,
               :order => "name ASC")
    end

    def by_opentransact(asset)
      Group.find_by_asset(asset)
    end
  end

  def opentransact?
    !asset.nil?
  end

  def admins
    admins = memberships.with_role('admin').map {|m| m.person}
    admins << owner if admins.empty?
    admins
  end

  def reserves
    accounts.where(reserve: true).map {|a| a.person}
  end

  def sum_reserves
    accounts.where(reserve: true).map(&:reserve_percent).inject(:+) || 0
  end

  def public?
    self.mode == PUBLIC
  end
  
  def private?
    self.mode == PRIVATE
  end
  
  def owner?(person)
    self.owner == person
  end
 
  def authorized_to_view_reqs?(person)
    privacy_setting.viewable_reqs? or Membership.exist?(person, self)
  end

  def authorized_to_view_offers?(person)
    privacy_setting.viewable_offers? or Membership.exist?(person, self)
  end

  def authorized_to_view_forum?(person)
    privacy_setting.viewable_forum? or Membership.exist?(person, self)
  end

  def authorized_to_view_members?(person)
    privacy_setting.viewable_members? or Membership.exist?(person, self)
  end

  ## Photo helpers
  def photo
    # This should only have one entry, but be paranoid.
    photos.find_all_by_primary(true).first
  end

  # Return all the photos other than the primary one
  def other_photos
    photos.length > 1 ? photos - [photo] : []
  end

  def main_photo
    photo.nil? ? Preference.group_image : photo.picture_url
  end

  def thumbnail
    photo.nil? ? Preference.group_image(:thumbnail) : photo.picture_url(:thumbnail)
  end

  def icon
    photo.nil? ? Preference.group_image(:icon) : photo.picture_url(:icon)
  end

  def bounded_icon
    photo.nil? ? Preference.group_image(:icon) : photo.picture_url(:icon)
  end

  # Return the photos ordered by primary first, then by created_at.
  # They are already ordered by created_at as per the has_many association.
  def sorted_photos
    # The call to partition ensures that the primary photo comes first.
    # photos.partition(&:primary) => [[primary], [other one, another one]]
    # flatten yields [primary, other one, another one]
    @sorted_photos ||= photos.partition(&:primary).flatten
  end
  
  
  private

  def changing_asset_name_only_allowed_if_empty
    unless new_record?
      if asset_changed?
        unless asset_was.blank?
          errors.add(:asset, "cannot be changed unless it is empty")
        end
      end
    end
  end

  def create_owner_membership
    mem = Membership.new( :status => Membership::PENDING )
    mem.person = self.owner 
    mem.group = self
    mem.roles = ['admin']
    mem.save
    Membership.accept(mem.person,mem.group)
  end

  def update_member_credit_limits
    if default_credit_limit_changed?
      transaction do
        memberships.each do |m|
          m.account.update_attributes!(:credit_limit => default_credit_limit)
        end
      end
    end
  end

  def log_activity
    activity = Activity.create!(:item => self, :person => Person.find(self.person_id))
    add_activities(:activity => activity, :person => Person.find(self.person_id))
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :login_or_oauth_required
  skip_before_filter :require_activation
  load_and_authorize_resource
  
  def index
    @body = "noajax"
    # XXX can't define abilities w/ blocks (accessible_by) http://github.com/ryanb/cancan/wiki/Upgrading-to-1.4
    @groups = Group.name_sorted_and_paginated(params[:page])

    respond_to do |format|
      format.html
    end
  end

  def show
    membership_display

    if membership
      if @group.adhoc_currency?
        @transactions = current_person.transactions.where(group_id: @group.id).limit(3)
      end
      @your_offers = current_person.offers_for_group(@group)
      @your_reqs = current_person.reqs_for_group(@group)
      @invitations = current_person.invitations.where(accepted_at: nil)
    end
    respond_to do |format|
      format.html do
        @forum = @group.forum
        @topics = Topic.where('1=0').paginate(:page => 1, :per_page => ajax_posts_per_page)
        @reqs = Req.where('1=0').paginate(:page => 1, :per_page => ajax_posts_per_page)
        @offers = Offer.where('1=0').paginate(:page => 1, :per_page => ajax_posts_per_page)
        unless @group.private_txns?
          @exchanges = @group.exchanges.paginate(:page => params[:page], :per_page => ajax_posts_per_page)
        end
        @memberships = Membership.where('1=0').paginate(:page => 1, :per_page => ajax_posts_per_page)
      end
      format.js {render :action => 'reject' if not request.xhr?}
      format.xml { render :xml => @group.to_xml(:methods => [:icon,:thumbnail], :only => [:id,:name,:description,:mode,:person_id,:created_at,:updated_at,:unit,:icon,:thumbnail]) }
    end

  end

  def new
    @photo = Photo.new
    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  def create
    @group.owner = current_person

    respond_to do |format|
      if @group.save
        flash[:success] = t('success_group_created')
        format.html { redirect_to(group_path(@group)) }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update_attributes(params[:group])
        flash[:notice] = t('notice_group_updated')
        format.html { redirect_to(group_path(@group)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      flash[:success] = t('success_group_deleted')
      format.html { redirect_to(groups_path) }
    end
  end
 
  def exchanges
    @exchanges = @group.exchanges.paginate(:page => params[:page], :per_page => ajax_posts_per_page)
    respond_to do |format|
      format.js {render :action => 'reject' if not request.xhr?}
    end
  end

  def people
    respond_to do |format|
      format.html { redirect_to group_path(@group, :anchor => 'people') }
    end
  end

  def members
    @body = "noajax"
    @memberships = Membership.custom_search(nil,
                                            @group,
                                            params[:page],
                                            RASTER_PER_PAGE,
                                            params[:search]
                                            )

    @pending = @group.pending_request.paginate(:page => params[:page],
                                          :per_page => RASTER_PER_PAGE)
    respond_to do |format|
      format.html
    end
  end

  def graphs
    @num_months = 6
    respond_to do |format|
      format.js {render :action => 'reject' if not request.xhr?}
    end
  end

  def photos
    #@group = Group.find(params[:id])
    @photos = @group.photos
    respond_to do |format|
      format.html
    end
  end
  
  def new_photo
    @photo = Photo.new
    respond_to do |format|
      format.html
    end
  end
  
  def save_photo
    #group = Group.find(params[:id])
    if params[:photo].nil?
      # This is mainly to prevent exceptions on iPhones.
      flash[:error] = t('error_browser_upload_fail')
      redirect_to(edit_group_path(@group)) and return
    end
    if params[:commit] == "Cancel"
      flash[:notice] = t('notice_upload_canceled')
      redirect_to(edit_group_path(@group)) and return
    end
    
    group_data = { :photoable => @group,
                    :primary => @group.photos.empty? }
    @photo = Photo.new(params[:photo].merge(group_data))
    
    respond_to do |format|
      if @photo.save
        flash[:success] = t('success_photo_uploaded')
        if @group.owner == current_person
          format.html { redirect_to(edit_group_path(@group)) }
        else
          format.html { redirect_to(group_path(@group)) }
        end
      else
        format.html { render :action => "new_photo" }
      end
    end
  end
  
  def delete_photo
    @group = Group.find(params[:id])
    @photo = Photo.find(params[:photo_id])
    @photo.destroy
    flash[:success] = t('success_photo_deleted_for_group') + " '#{@group.name}'"
    respond_to do |format|
      format.html { redirect_to(edit_group_path(@group)) }
    end
  end
  
  protected

  def membership
    @membership ||= Membership.mem(current_person,@group)
  end

  def membership_display
    if membership
      @add_membership_display = 'hide'
      @membership_display = ''
      @membership_id = membership.id
    else
      @add_membership_display = ''
      @membership_display = 'hide'
      @membership_id = ""
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  
  def group_owner?(person,group)
    person == group.owner
  end
  
  # Return a group's image link.
  # The default is to display the group's icon linked to the profile.
  def group_image_link(group, options = {})
    link = options[:link] || group
    image = options[:image] || :icon
    unless options[:image_options].nil?
      title_prefix = options[:image_options][:class] == 'default-group-link' ? t('return_to') : ''
    end
    group_title = (title_prefix || '') + h(group.name)
    image_options = { :title => group_title, :alt => group_title }
    unless options[:image_options].nil?
      image_options.merge!(options[:image_options]) 
    end
    link_options =  { :title => h(group.name) }
    unless options[:link_options].nil?                    
      link_options.merge!(options[:link_options])
    end
    content = image_tag(group.send(image), image_options)
    # This is a hack needed for the way the designer handled rastered images
    # (with a 'vcard' class).
    if options[:vcard]
      content = %(#{content}#{content_tag(:span, h(group.name), 
                                                 :class => "fn" )})
    end
    link_to(content, link, link_options)
  end
  
  def group_link(group)
    link_to(h(group.name), group_path(group))
  end

  def delete_membership_link(person,group)
    membership = Membership.mem(person,group)
    if membership
      membership_path(membership)
    else
      "#"
    end
  end

  def reqs_options
    options_for_select([[t('reqs.index.active_requests'),1],[t('filter_categories'),2],[t('filter_neighborhoods'),3]])
  end

  def offers_options
    options_for_select([[t('offers.index.active_offers'),1],[t('filter_categories'),2],[t('filter_neighborhoods'),3]])
  end

  def memberships_options
    options_for_select([[t('all_members'),1],[t('filter_categories'),2],[t('filter_neighborhoods'),3]])
  end
end

app/views/groups/_categories.html.erb
<span class='category_filter'>by category
<%= 
    collection_select( filtered_obj, 
                       'category_ids', 
                       @all_categories, 
                       :id, 
                       :long_name, 
                       { :include_blank => true, :selected => selected_category }
                     ) 
%>
</span>

app/views/groups/_exchange.html.erb
<% member = Membership.mem(exchange.worker,exchange.group) %>
<li>
  <div class="profile-image">
    <%= image_link exchange.worker, :link => member, :link_options => {:class => "show-follow"}, :image_options => {:class => "photo"}, :image => :thumbnail %>
    <%= image_tag "icons/switch.gif", :class => "icon", :alt => "Street Cred" %>
  </div>
  <p>
  <% unless exchange.group.nil? %>
    <%= membership_link member, :class => "url fn show-follow" %> <%= t('earned') + " " + nice_decimal(exchange.amount) + " " + exchange.group.unit + " " + t('for') %> <%= link_to h(exchange.metadata.name), exchange.metadata, :class => "show-follow" %>
  <%- end -%>
  </p>
  <p class="meta published">
    <%= t( 'ago_time', :date=> time_ago_in_words(exchange.created_at)).capitalize %> 
  </p>

</li>

app/views/groups/_forum_canvas.html.erb
        <h2><%= t('groups.show.discussion_topics') %><%= waiting_image %></h2>
        <ol class="list forum full">
          <%= render :partial => 'topics/topic', :collection => @topics %>
        </ol>
        <%- if logged_in? -%>
          <h3><%= t('groups.show.add_a_new_topic') %></h3>
          <%= form_for :topic, :url => forum_topics_path(@forum), :html => {:id => 'new_topic'} do |f| %>
            <div class="form_row">
              <%= f.text_field :name %>
              <%= submit_tag t('button_submit'), :class => "button" %>
            </div>
          <% end %>
        <%- end -%>

app/views/groups/_forum_form.html.erb
      <div id="forum_form"></div>

app/views/groups/_group.html.erb
<li class="vcard person">
  <div class="profile-image">
    <%= group_image_link group, :class => "photo", :image => :thumbnail %>
  </div>
  <p><%= link_to(group.name, group, :class => "url fn") %></p>
  <%= display(group.description, :class => "note") %>
</li>

app/views/groups/_home_canvas.html.erb
<div class="profile vcard">
  <%- if @membership && @membership.is?(:admin) -%>
    <%= render 'shared/group_admin_alert' %>
  <%- end -%>
  <div class="row">
    <div class="span9">
<%- if @membership %>
      <%= render :partial => 'invitations' %>
      <%- if @group.adhoc_currency? %>
        <%= render :partial => 'shared/account', :locals => {:account => @membership.account, :html_classes => 'show-follow'} %>
        <%- if @transactions.length > 0 %>
          <h2><%= t('transacts.index.header') %></h2>
          <ul class="list activity full">
            <%= render :partial => 'shared/transact', :collection => @transactions, :locals => {:ajaxified => true} %> 
          </ul>
          <% if @group.asset %>
            <%= link_to t('see_all'), transacts_path(@group.asset), :target => '_blank' %>
          <% end %>
        <%- end -%>
      <%- end -%>
      <h2><%= t('home._dashboard.offers') %></h2>
      <%- if @your_offers.length > 0 %>
        <ul class="list activity full">
          <%= render :partial => '/offers/offer', :collection => @your_offers %>
        </ul>
      <%- else -%>
        <h3><%= t('offers.index.nooffers') %></h3>
      <%- end %>
      <h2><%= t('home._dashboard.requests') %></h2>
      <%- if @your_reqs.length > 0 %>
        <ul class="list activity full">
          <%= render :partial => '/reqs/req', :collection => @your_reqs %>
        </ul>
      <%- else -%>
        <h3><%= t('reqs.index.noreqs') %></h3>
      <%- end %>
      <br />
<%- end -%>
      <%= render 'toolbox' %>
    </div>
    <%= render 'shared/minifeed' %>
  </div>
</div>

app/views/groups/_invitations.html.erb
<%- unless @invitations.empty? -%>
   <h2><%= t('home._invitations.header') %></h2>
   <ul class="list requests small">
     <%- @invitations.each do |invitation| -%>
       <li>
         <div class="profile-image">
           <%= group_image_link invitation.group %>
         </div>
         <p><%= t('home._invitations.invitation_for') %>
         <%= group_link invitation.group %></p>
         <p class="meta published">
           <%= time_ago_in_words(invitation.created_at) %> 
           <%= t('ago') %>
         </p>
         <p>
           <%= link_to t('home._invitations.respond'), edit_invitation_path(invitation) %> |
           <%= link_to t('home._invitations.view_group'), group_path(invitation.group) %>
         </p>
       </li>
     <%- end -%>
   </ul>
 <%- end -%>

app/views/groups/_toolbox.html.erb
  <%- unless @membership %>
    <div class="group-photo span3">
      <%= image_tag @group.main_photo, :class => "profile-image photo", :alt => h(@group.name) %>
    </div>
    <%= h(@group.description) %>
  <%- end -%>
<div class="toolbox">
  <ul class="tools">
    <%- if @group.adhoc_currency? %>
      <%- if @membership %>
        <%- if @membership.account.credit_limit %>
          <li>
            <%= t('groups.show.your_credit_limit') %>
            <%= nice_decimal(@membership.account.credit_limit) %>
            <%= @group.unit %>
          </li>
        <%- end -%>
      <%- else -%>
        <%- if @group.default_credit_limit %>
          <li>
            <%= t('groups.show.default_credit_limit') %>
            <%= nice_decimal(@group.default_credit_limit) %>
            <%= @group.unit %>
          </li>
        <%- end -%>
      <%- end -%>
    <%- end -%>
    <%- if @membership %>
      <li>
        <%= link_to t('home.index.edit_your_preferences'), edit_member_preference_path(@membership.member_preference), :class => "show-follow" %>
      </li>
    <%- end -%>
    <%- if Membership.pending?(current_person, @group) -%>
      <li>
        <%= t('groups.show.you_have_requested_to_be_a_member_of') %> <strong><%= h @group.name %></strong>
      </li>
    <%- end -%>
    <%- if group_owner?(current_person,@group) -%>
      <li>
        <%= t('groups.show.you_are_group_admin') %>
        <%= link_to t('groups.show.delete_it'), group_path(@group), :confirm => t('are_you_sure'), :method => :delete %>
      </li>
      <li>
        <%= t('groups.show.mode') %> <%= @group.get_groups_modes[@group.mode][0] %>
      </li>
      <% if @group.asset %>
        <li>
          <%= t('groups.show.asset_name') %> <%= link_to @group.asset, transacts_path(@group.asset), :target => '_blank' %>
        </li>
      <% end %>
    <%- end -%>
    <%= render :partial => 'membership' %>
  </ul>
</div>

app/views/groups/exchanges.js.erb
$('#exchanges_canvas').html("<%= escape_javascript(render :partial => 'exchanges_canvas') %>");
$('#posts_per_page').show();

app/views/groups/graphs.js.erb
$('#home_canvas').html("<%= escape_javascript(render :partial => 'shared/graphs') %>");
<%= render :partial => '/shared/flash_messages', :locals => {:canvas_id => 'home_canvas'} %>

app/views/groups/photos.html.erb
<% unless @photos.empty? %>
<ul style="list-style-type: none;">
<% @photos.each do |photo| %>
  <li><%= image_tag(photo.picture_url) %></li>
<% end %>
</ul>
<% end %>

app/views/groups/show.html.erb
<%= render :partial => 'shared/jscript', :locals => { :jscript_file_name => 'group' } %>

<div>
  <ul id="nav-js" class="nav nav-tabs">
    <li class="active"><a href="#tab_home" data-toggle="tab"><%= t("groups.show.home") %></a></li>
<%- if @group.adhoc_currency? and not @group.private_txns? -%>
    <li><a href="#tab_exchanges" data-toggle="tab"><%= t("groups.show.exchanges") %></a></li>
<%- end -%>
<%- if @group.enable_forum? -%>
    <li><a href="#tab_forum" data-toggle="tab"><%= t("groups.show.forum") %></a></li>
<%- end -%>
    <li><a href="#tab_requests" data-toggle="tab"><%= t("groups.show.requests") %></a></li>
    <li><a href="#tab_offers" data-toggle="tab"><%= t("groups.show.offers") %></a></li>
    <li><a href="#tab_people" data-toggle="tab"><%= t("groups.show.people") %></a></li>
  </ul>


  <div class="tab-content">
    <div class="tab-pane active" id="tab_home">
      <div id="home_canvas">
      <%= render 'home_canvas' %>
      </div>
    </div>
<%- if @group.adhoc_currency? and not @group.private_txns? -%>
    <div class="tab-pane" id="tab_exchanges">
      <div id="exchanges_canvas">
      <%= render 'exchanges_canvas' %>
      </div>
    </div>
<%- end -%>
<%- if @group.enable_forum? -%>
    <div class="tab-pane" id="tab_forum">
      <div id="forum_canvas">
      <%= render '/forums/forum_canvas' %>
      </div>
      <%= render 'forum_form' %>
    </div>
<%- end -%>
    <div class="tab-pane" id="tab_requests">
      
      <div id="requests_filter">

        <h2 style="display:inline;"><%= t('reqs.index.header') %> &nbsp;</h2><%= waiting_image %>
        
        <span class="pos-super">
          <%= t('view_by') %> 
          &nbsp;
        </span>

        <%= select_tag "filter_reqs_by", reqs_options %>
        
        <%= render :partial => '/shared/categories', :locals => {:filtered_obj => 'req', :selected_category => (@selected_category.nil? ? 0 : @selected_category.id)} %>
        
        <%= render :partial => '/shared/neighborhoods', :locals => {:filtered_obj => 'req', :selected_neighborhood => (@selected_neighborhood.nil? ? 0 : @selected_neighborhood.id)} %>
        
        <span class="pos-super">
          &nbsp;<%= t('or') %>&nbsp;&nbsp;
          <%= link_to t('button_new_req'), new_group_req_path(@group), {:class => 'show-follow btn btn-primary'} %>
        </span>
      
      </div>
      
      <div id="reqs_canvas">
        <%= render '/reqs/reqs_canvas' %>
      </div>

    </div>
    <div class="tab-pane" id="tab_offers">
      <div id="offers_filter">

        <h2 style="display:inline;"><%= t('groups.show.offers') %> &nbsp;</h2><%= waiting_image %>
          
        <span class='pos-super'>
          <%= t('view_by') %> 
          &nbsp;
        </span>
        
        <%= select_tag "filter_offers_by", offers_options %>
        
        <%= render :partial => '/shared/categories', :locals => {:filtered_obj => 'offer', :selected_category => (@selected_category.nil? ? 0 : @selected_category.id)} %>
        
        <%= render :partial => '/shared/neighborhoods', :locals => {:filtered_obj => 'offer', :selected_neighborhood => (@selected_neighborhood.nil? ? 0 : @selected_neighborhood.id)} %>
      
        <span class='pos-super'>
          &nbsp;<%= t('or') %>&nbsp;&nbsp;
          <%= link_to t('button_new_offer'), new_group_offer_path(@group), {:class => 'show-follow btn btn-primary'} %>
        </span>
        
      </div>
      <div id="offers_canvas">
      <%= render '/offers/offers_canvas' %>
      </div>
    </div>
    
    <div class="tab-pane" id="tab_people">
      <div id="people_filter">
        <h2 style="display:inline;"><%= t('groups.show.people') %><%= waiting_image %></h2>
        <%= t('view_by') %> <%= select_tag "filter_memberships_by", memberships_options %>
        <%= render :partial => '/shared/categories', :locals => {:filtered_obj => 'person', :selected_category => (@selected_category.nil? ? 0 : @selected_category.id)} %>
        <%= render :partial => '/shared/neighborhoods', :locals => {:filtered_obj => 'person', :selected_neighborhood => (@selected_neighborhood.nil? ? 0 : @selected_neighborhood.id)} %>
      </div>
      <div id="people_canvas">
      <%= render '/memberships/members_canvas' %>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>

</div>