config/routes.rb
Oscurrency::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :person_sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :member_preferences
  resources :neighborhoods, :only => [:show]
  resources :invitations, :only => [:edit, :update]
  resources :privacy_settings, :only => [:update]
  resources :posts, :only => [:index]

  # XXX in 2.3.x, this was easier -> map.resources :transacts, :as => "transacts/:asset"
  get    "transacts(/:asset)(.:format)"          => "transacts#index",   :as => 'transacts'
  get    "transacts(/:asset)/new"      => "transacts#new",     :as => 'new_transact'
  get    "transacts(/:asset)/:id(.:format)"      => "transacts#show",    :as => 'transact'
  post   "transacts(/:asset)(.:format)"          => "transacts#create",  :as => 'transacts'
  #get    "transacts/[:asset]/:id/edit" => "transacts#edit",    :as => 'edit_transact'
  #put    "transacts/[:asset]/:id"      => "transacts#update",  :as => 'transact'
  delete "transacts(/:asset)/:id(.:format)"      => "transacts#destroy", :as => 'transact'

  resources :groups, :shallow => true do
    member do
      post :join
      post :leave
      get :people
      get :exchanges
      get :members
      get :graphs
      get :photos
      post :new_photo
      post :save_photo
      delete :delete_photo
    end
    resources :memberships
    resources :reqs
    resources :offers
    resource :forum
  end

  resources :bids
  resources :reqs do
    member do 
      post :deactivate
    end
    resources :bids
  end

  resources :offers do
    member do
      get :new_photo
      post :save_photo
    end
  end
  resources :categories

  resources :memberships do
    member do
      delete :unsuscribe
      post :suscribe
    end
  end

  resources :searches
  resources :activities
  resources :connections
  resources :photos do
    collection do
      get :default_profile_picture
      put :update_default_profile_picture
      get :default_group_picture
      put :update_default_group_picture
    end
  end
  resources :messages do
    collection do
      get :sent
      get :trash
      get :recipients
    end
    member do
      get :reply
      put :undestroy
    end
  end
  resources :people do
    member do
      get :verify_email
      get :su
      get :unsu
      get :invite
      post :send_invite
      get :common_contacts
    end
    resources :messages
    resources :accounts
    resources :exchanges
    resources :addresses do
      member do
        post :choose
      end
    end
    resources :photos
    resources :connections
  end

  match 'people/verify/:id' => 'people#verify_email'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  match '/signup' => 'people#new', :as => :signup
  match '/login' => 'person_sessions#new', :as => :login
  match '/logout' => 'person_sessions#destroy', :as => :logout
  match '/refreshblog' => 'feed_posts#refresh_blog', :as => :refreshblog
  match '/about' => 'home#about', :as => :about
  match '/practice' => 'home#practice', :as => :practice
  match '/steps' => 'home#steps', :as => :steps
  match '/questions' => 'home#questions', :as => :questions
  match '/contact' => 'home#contact', :as => :contact
  match '/agreement' => 'home#agreement', :as => :agreement
  resources :oauth_clients
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth/token' => 'oauth#token', :as => :token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/scopes' => 'transacts#scopes', :as => :scopes
  match '/oauth/revoke' => 'oauth#revoke', :as => :revoke
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/about_user' => 'transacts#about_user', :as => :about_user
  match '/user_info' => 'transacts#user_info', :as => :user_info
  match '/wallet' => 'transacts#wallet', :as => :wallet
  match '/.well-known/host-meta' => 'home#host_meta', :as => :host_meta
  match '/home/show/:id' => 'home#show'
  root :to => 'home#index'
  match '/' => 'home#index', :as => :home
end

app/controllers/oauth_clients_controller.rb
class OauthClientsController < ApplicationController
  before_filter :login_required, :except => [:create]
  before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]
 
  def index
    @client_applications = current_person.client_applications
    @tokens = current_person.tokens.find :all, :conditions => 'oauth_tokens.invalidated_at is null and oauth_tokens.authorized_at is not null'
  end

  def new
    @client_application = ClientApplication.new
  end

  def create
    respond_to do |format|
      format.html do
        if current_person
          @client_application = current_person.client_applications.build(params[:client_application])
          if @client_application.save
            flash[:notice] = t('notice_registered_the_information_successfully')
            redirect_to :action => "show", :id => @client_application.id
          else
            render :action => "new"
          end
        end
      end
      format.json do
        response.headers["Cache-Control"] = "private, no-store, max-age=0, must-revalidate"
        redirect_uri = ""
        begin
          raise "client_name" if params[:client_name].nil?
          raise "client_url" if params[:client_url].nil?
          raise "client_description" if params[:client_description].nil?
          raise "type" if params[:type].nil?

          if params[:application_type] && 'noredirect' == params[:application_type]
            redirect_uri = request.protocol + request.host_with_port + "/transacts"
          elsif params[:redirect_url]
            redirect_uri = params[:redirect_url]
          end
          @client_application = ClientApplication.new :name => params[:client_name], :description => params[:client_description], :url => params[:client_url], :callback_url => redirect_uri, :person => nil
          if @client_application.save!
            render :json => @client_application.as_json
          else
            render :json => {:error => "Bad Request"}.as_json, :status => 400
          end
        rescue => e
          render :json => {:error => "Missing parameter: #{e}"}.as_json, :status => 400
        end
      end
    end
  end
  
  def show
  end

  def edit
  end
  
  def update
    if @client_application.update_attributes(params[:client_application])
      flash[:notice] = t('notice_updated_the_client_information_successfully')
      redirect_to :action => "show", :id => @client_application.id
    else
      render :action => "edit"
    end
  end

  def destroy
    @client_application.destroy
    flash[:notice] = t('notice_destroyed_the_client_application_registration')
    redirect_to :action => "index"
  end
  
  private
  def get_client_application
    unless @client_application = current_person.client_applications.find(params[:id])
      flash.now[:error] = t('error_wrong_application_id')
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/helpers/oauth_clients_helper.rb
module OauthClientsHelper
end

app/views/oauth_clients/_capability.html.erb
<img src="<%= capability.action_icon_uri %>" title="<%= capability.long_action_name %>">

app/views/oauth_clients/_form.html.erb
<%= f.text_field :name, label: "Name" %>
<%= f.text_field :url, label: "Main Application URL" %>
<%= f.text_field :callback_url, label: "Callback URL" %>
<%= f.text_field :support_url, label: "Support URL" %>

app/views/oauth_clients/edit.html.erb
<h1>Edit your application</h1>
<%= bootstrap_form_for @client_application, :url => oauth_client_path(@client_application), :html => {:method => :put}  do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.actions do %>
    <%= f.primary t('button_update') %>
  <% end %>
<% end %>
<%= link_to 'Show', oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>

app/views/oauth_clients/index.html.erb
<div class="alert"><%= flash[:notice] %></div>
<h1>OAuth Client Applications</h1>
<% unless @tokens.empty? %>
<p>The following tokens have been issued to applications in your name</p>
<table>
  <tr><th>Application</th><th>Capabilities</th><th>Issued</th><th>&nbsp;</th></tr>
  <% @tokens.each do |token|%>
    <% content_tag_for :tr, token do %>
      <td><%= link_to token.client_application.name, token.client_application.url %></td>
      <td><%= render :partial => 'capability', :collection => token.capabilities %></td>
      <td><%= token.authorized_at %></td>
      <td>
        <%= form_tag :controller => 'oauth', :action => 'revoke' do %>
        <%= hidden_field_tag 'token', token.token %>
        <%= submit_tag "Revoke!" %>
        <% end %>
      </td>
    <% end %>
  <% end %>
  
</table>
<% end %>
<h3>Application Developers</h3>
<% if @client_applications.empty? %>
  <p>
    Do you have an application you would like to register for use with us using the <a href="http://oauth.net">OAuth</a> standard?
  </p>
  <p>
    You must register your web application before it can make OAuth requests to this service
  </p>
<% else %>
  <p>
    You have the following client applications registered:
  </p>
  <% @client_applications.each do |client|%>
    <% div_for client do %>
      <%= link_to client.name, oauth_client_path(client) %>- 
        <%= link_to 'Edit', edit_oauth_client_path(client) %>
        <%= link_to 'Delete', oauth_client_path(client), :confirm => "Are you sure?", :method => :delete %>
    <% end %>
  <% end %>
<% end %>
<br />
<h3><%= link_to "Register your application", :action => :new %></h3>

app/views/oauth_clients/new.html.erb
<h1>Register a new application</h1>
<%= bootstrap_form_for @client_application, :url => { :action => :create } do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= f.actions do %>
    <%= f.primary t('button_create') %>
  <% end %>
<% end %>

app/views/oauth_clients/show.html.erb
<h1>OAuth details for <%=@client_application.name %></h1>
<p>
  <strong>Consumer Key:</strong>
  <code><%=@client_application.key %></code>
</p>
<p>
  <strong>Consumer Secret:</strong>
  <code><%=@client_application.secret %></code>
</p>
<p>
  <strong>Request Token URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.request_token_path %></code>
</p>
<p>
  <strong>Access Token URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.access_token_path %></code>
</p>
<p>
  <strong>Authorize URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.authorize_path %></code>
</p>

<p>
  We support hmac-sha1 (recommended) as well as plain text in ssl mode.
</p>
<%= link_to 'Edit', edit_oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>